DROP TABLE XE;
CREATE TABLE XE (
    XE_NO NUMBER NOT NULL PRIMARY KEY,
    XE_CONTENT VARCHAR2(100 BYTE) NOT NULL,
    XE_CREATED_AT TIMESTAMP
);

CREATE SEQUENCE XE_SEQ NOCACHE;

INSERT INTO XE VALUES(XE_SEQ.NEXTVAL, '월요일', SYSTIMESTAMP);
INSERT INTO XE VALUES(XE_SEQ.NEXTVAL, '화요일', SYSTIMESTAMP);
INSERT INTO XE VALUES(XE_SEQ.NEXTVAL, '수요일', SYSTIMESTAMP);